### PR TITLE
Update Apache and PHP7.4, switch to stable UPX and replace ApacheKill.exe

### PR DESCRIPTION
**Pull request by hauk92**
PHP comes from [here](https://www.apachelounge.com/viewtopic.php?t=6359) and is based on https://github.com/remicollet/php-src-security.

I still get warnings from the indexmenu plugin (see https://github.com/samuelet/indexmenu/issues?q=is%3Aopen+PHP+8). The plugin is pretty popular so I opted for updating PHP7.4 instead of switching to 8.x.

I assume apachekill is a relict from previous Windows versions (XP?). I replaced it since is is _very_ old and does not seem to work with a 64bit version of Apache. "taskkill /im mapache.exe /f /t" should do the same.

### CODE REVIEW

**Comment by Klap-in** [comment]
> I still get warnings from the indexmenu plugin (see https://github.com/samuelet/indexmenu/issues?q=is%3Aopen+PHP+8). The plugin is pretty popular so I opted for updating PHP7.4 instead of switching to 8.x.

Some where already solved, the other one I solved today. If you have more of them, I like to hear.

**Comment by hauk92** [comment]
> > I still get warnings from the indexmenu plugin (see https://github.com/samuelet/indexmenu/issues?q=is%3Aopen+PHP+8). The plugin is pretty popular so I opted for updating PHP7.4 instead of switching to 8.x.
> 
> Some where already solved, the other one I solved today. If you have more of them, I like to hear.

Thank you! I have no more errors. Maybe the builds should be swapped to PHP8.x (and 64bit)?

I have briefly tested this on Windows 10 and in the Microsoft provided Windows 11 virtual machine.

I did not test the github actions build. I tried using unrar-free on Ubuntu but it was unfortunately not able to extract the apache.rar.

Here are two zips anyone wants to test the resulting servers. One with PHP7.4 and one with the current PHP8.2 and in 64bit.

[DokuWikiStick-PHP7.4-x86.zip](https://github.com/splitbrain/dokuwiki-stickbuilder/files/12643906/DokuWikiStick-PHP7.4-x86.zip)
[DokuWikiStick-PHP8.2-x64.zip](https://github.com/splitbrain/dokuwiki-stickbuilder/files/12643907/DokuWikiStick-PHP8.2-x64.zip)

**Comment by splitbrain** [comment]
I updated to 64bit PHP8.2 based on your other branch. Thanks a lot!

**Comment by Klap-in** [comment]
I thinking this page needs still some love, @hauk92 could you maybe have a look? https://www.dokuwiki.org/install:dokuwiki_on_a_stick

**Pull request closed without merging**
